#
#  Configuration for motion
#
gulp:
  start:
    development:
      gulp:
        - 'lint'
        - 'build'
        - 'watch'
        - 'livereload-start'
        - 'server-start'
        - 'tests'
#        - 'livereload-all'
      build:
        - 'less'
        - 'js'
        - 'locales'
#        - 'jsdoc'
      tests:
        - 'test-modules'
      lint:
        - 'ejslint'
        - 'eslint'
        - 'jsonlint'
        - 'yamllint'
        - 'puglint'
        - 'ejslint'
      server:
        - 'server-changed'
        - 'tests'
    staging:
      gulp:
        - 'watch'
        - 'server-start'
      build: []
      tests: []
      lint: []
      server:
        - 'server-changed'
      watch:
        - 'server'
    production:
      gulp:
        - 'build'
        - 'server-start'
      build:
        - 'less'
        - 'js'
        - 'locales'
      tests: []
      lint: []
      server:
        - 'server-changed'
  watch:
    eslint:
      - '*.js'
      - '.eslintrc.js'
      - 'gulp/**/*.js'
      - 'lib/**/*.js'
      - 'modules/**/*.js'
    js:
      - 'modules/*/js/*.js'
    jsdoc:
#      - 'nofile.js'
      - '*.js'
      - 'gulp/**/*.js'
      - 'lib/**/*.js'
      - 'modules/**/*.js'
    jsonlint:
      - '**/*.json'
      - '.lesshintrc'
      - '!src/locales/*.json'
      - '!modules/**/locales/*.json'
    locales:
      - 'src/locales/*.json'
      - 'modules/**/locales/*.json'
    yamllint:
      - '**/*.yaml'
      - '**/*.yml'
    ejslint-livereload:
      - '**/*.ejs'
    less:
      - 'src/less/**/*.less'
      - 'modules/**/*.less'
    puglint:
      - '**/*.pug'
    server:
      - 'server.js'
      - 'modules/*/server/*.js'
      - 'modules/*/*.yaml'
    livereload:
      - 'public/**/*.html'
      - 'public/img/**/*.*'
      - 'public/**/*.css'
      - 'modules/**/*.ejs'
      - 'modules/**/*.pug'
    livereload-all:
      - 'public/**/*.js'
      - 'locales/**/*.*'
    test-modules:
      - 'index.js'
      - 'modules/**/tests/model/*.*'
      - 'modules/**/tests/server/*.*'
      - 'modules/**/views/**/*.*'
      - 'htdocs/js/**/*.js'
  tests:
    modules:
      - 'modules/**/tests/model/*.js'
      - 'modules/**/tests/server/*.js'
      - 'modules/**/tests/views/*.js'
  build:
    jsdoc:
      src:
        - '*.js'
        - 'gulp/**/*.js'
        - 'lib/**/*.js'
        - 'modules/**/*.js'
        - 'src/**/*.js'
      dest: 'docs/jsdoc'
    js:
      src:
        - 'modules/*/js/*.js'
      dest: 'public'
      replace:
        'modules/(.+/)js/.+': '$1'
    less:
      src:
        - 'src/less/app.less'
        - 'modules/*/less/layout.less'
      dest: 'public'
    locales:
      dest: 'locales'
    deploy:
      src:
        - 'CHANGELOG.md'
        - 'configuration.yaml'
        - 'Dockerfile'
        - 'LICENSE'
        - 'package.json'
        - 'README.md'
        - 'server.js'
        - 'lib/**/*'
        - 'locales/*'
        - 'modules/*/*.json'
        - 'modules/*/*.yaml'
        - 'modules/*/server/**/*'
        - 'modules/*/views/**/*'
        - 'public/**/*'
      dest: 'deploy'

server:
  server: ./server.js
  docroot: ./public
  modules: ./modules
  verbose: false
  httpsKey: ./key/selfsigned.key
  httpsCert: ./key/selfsigned.crt
  lifereloadHost: motion
